version: '3'
services:
  frontend:
    build: ./frontend
    expose:
      - ${NGINX_PORT}
    ports:
      - ${NGINX_PORT}:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
  postgres:
    image: postgres:14.0
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
